# Configuration file for mise, a task runner and environment manager.
# See https://mise.jdx.dev for more information.
#:schema https://mise.jdx.dev/schema/mise.json

[tools]
uv = "latest"

[settings]
python.uv_venv_auto = "create|source"
idiomatic_version_file_enable_tools = ["python"]

[env]
_.file = ".env"
BOT_ENV = "development"
BOT_CONFIG = "./settings.toml"

[hooks]
enter = { task = "install" }

[tasks.install]
description = "Install dependencies and hooks"
run = ["uv sync --all-groups", "uv run prek install"]

[tasks.format]
description = "Format the code"
run = ["uv run ruff format"]

[tasks.lint]
description = "Lint the code"
run = ["uv run ruff check"]

[tasks.type]
description = "Run type checks"
run = ["uv run ty check"]

[tasks.check]
description = "Run all checks"
depends = ["format --check", "lint", "type"]

[tasks."check:fix"]
description = "Fix all issues"
depends = ["format", "lint --fix", "type --fix"]

[tasks.dev]
description = "Start the bot"
depends = ["type"]
run = "uv run python -OO -m bot"

[tasks.prek]
description = "Run prek hooks"
run = ["uv run prek run --all-files"]

[tasks."prek:update"]
description = "Update prek hooks"
run = ["uv run prek update --freeze"]
