[tools]
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]

[env]
_.file = '.env'
BOT_ENV = "development"
BOT_CONFIG = "./settings.toml"

[tasks.install]
description = "Install dependencies and hooks"
run = ["uv sync --all-groups", "uv run prek install"]

[tasks.check]
description = "Check for linting and formatting issues"
run = ["uv run ruff check", "uv run ruff format --check"]

[tasks.fix]
description = "Fix linting and formatting issues"
run = ["uv run ruff check --fix", "uv run ruff format"]

[tasks.typecheck]
description = "Run type checks"
run = ["uv run ty check"]

[tasks.start]
description = "Start the bot"
depends = ["typecheck"]
run = "uv run python -OO -m bot"

[tasks.prek]
description = "Run prek hooks"
run = ["uv run prek run --all-files"]

[tasks.prek-update]
description = "Update prek hooks"
run = ["uv run prek auto-update"]
