# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
default_stages = ["pre-commit"]

[update]
cooldown_days = 7
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-vcs-permalinks" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "93c7b51d860138c34a0613756c0151209b88d56f"  # frozen: v4.17.0
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch" },
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "57b21406f092110c18776e39b0bda50d37c945c8"  # frozen: v2.4.3
hooks = [
  { id = "codespell" },
]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "451b56af716f9f0d0c2b816503a3fd0cf8b036fa"  # frozen: v1.29.0
hooks = [
  { id = "zizmor" },
]

[[repos]]
repo = "https://github.com/rvben/rumdl-pre-commit"
rev = "344543e77e653d3500a98ffd56cf41bcb92dc05c"  # frozen: v0.2.53
hooks = [
  { id = "rumdl-fmt" },
  { id = "rumdl" },
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "7fd33d1d0a5b52dcc5aaae94c68cc90a9926271e"  # frozen: v1.2.10
hooks = [
  { id = "tombi-format" },
  { id = "tombi-lint" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "8d582f54b8e4cc5a61a85eeed1f54bbdb1e294fc"  # frozen: 0.12.3
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "7c55798a78262d14b2074abf623d8a992ebb70d4"  # frozen: v0.16.2
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check", args = ["--fix"] },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "d8494b3a705ddc24569d31316df8fab801c04b77"  # frozen: v0.0.70
hooks = [
  { id = "ty" },
]
