# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
default_stages = ["pre-commit"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-vcs-permalinks" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.16.4"
hooks = [{ id = "commitizen" }, { id = "commitizen-branch" }]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.2"
hooks = [{ id = "codespell" }]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.26.1"
hooks = [{ id = "zizmor" }]

[[repos]]
repo = "https://github.com/rvben/rumdl-pre-commit"
rev = "v0.2.22"
hooks = [{ id = "rumdl" }, { id = "rumdl-fmt" }]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "v1.1.5"
hooks = [{ id = "tombi-format" }, { id = "tombi-lint" }]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.11.24"
hooks = [{ id = "uv-lock" }]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.19"
hooks = [{ id = "ruff-check", args = ["--fix"] }, { id = "ruff-format" }]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "v0.0.53"
hooks = [{ id = "ty" }]
