# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
default_stages = ["pre-commit"]

[update]
cooldown_days = 7
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-vcs-permalinks" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "d910b66e2686a3ef6c3f438dec0f63ba3cf8d7ee"  # frozen: v4.18.0
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch" },
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "57b21406f092110c18776e39b0bda50d37c945c8"  # frozen: v2.4.3
hooks = [
  { id = "codespell" },
]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "451b56af716f9f0d0c2b816503a3fd0cf8b036fa"  # frozen: v1.29.0
hooks = [
  { id = "zizmor" },
]

[[repos]]
repo = "https://github.com/rvben/rumdl-pre-commit"
rev = "00c9d9edd7a5d4cb8241c158888c015d71873889"  # frozen: v0.2.60
hooks = [
  { id = "rumdl-fmt" },
  { id = "rumdl" },
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "dd68bbd8cdd8891c942fb6f33a6e87a477b2c375"  # frozen: v1.4.1
hooks = [
  { id = "tombi-format" },
  { id = "tombi-lint" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "b84c4a0a90bd58c7d82ae8f0d4d5e77b1ddd3ce6"  # frozen: 0.12.5
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "aab412d509121cb5f7533134b7e67f9fab59c682"  # frozen: v0.16.4
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check", args = ["--fix"] },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "1241d80d7f628b8b0c60540b7a8c83b947136a4f"  # frozen: v0.0.74
hooks = [
  { id = "ty" },
]
