[project]
name = "template-bot"
version = "0.1.0"
description = "A template bot for Discord written in Python"
readme = "README.md"
requires-python = ">=3.14"
authors = [
  { name = "Keksi", email = "hello@keksi.dev" },
]
dependencies = [
  "hikari-lightbulb>=3.2.6",
  "hikari[speedups]>=2.6.0",
  "pydantic-settings>=2.15.0",
  "tortoise-orm[accel,asyncpg]>=1.1.8",
  "uvloop>=0.23.0",
]

[dependency-groups]
dev = [
  "commitizen>=4.19.2",
  "prek>=0.5.5",
  "ruff>=0.17.0",
  "rumdl>=0.2.79",
  "tombi>=1.8.1",
  "ty>=0.0.86",
]
docs = [
  "zensical>=0.0.69",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true

[tool.ruff]
cache-dir = "~/.cache/ruff"
line-length = 120
output-format = "grouped"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint]
preview = true
select = [
  "correctness",
  "suspicious",
  "complexity",
  "performance",
  "style",
  "security",
]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.rumdl]
cache-dir = "~/.cache/rumdl"
line-length = 200
respect-gitignore = true

[tool.rumdl.per-file-flavor]
"docs/**/*.md" = "mkdocs"

[tool.tombi.files]
exclude = ["uv.lock"]
